# Generated by Django 4.1 on 2022-08-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_gallery_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.OneToOneField(blank=True, default=None, on_delete=models.SET(None), to='product.author'),
        ),
    ]
