# Generated by Django 4.1 on 2022-08-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_product_author_product_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=models.SET(None), to='product.author'),
        ),
    ]
