# Generated by Django 4.1 on 2022-08-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_product_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to=1, null=True, on_delete=models.SET(None), to='product.author'),
        ),
    ]
